version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: user_loan_match
    environment:
      POSTGRES_DB: user_loan_match
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent! Data safe

volumes:
  postgres_data:
